#!/usr/bin/sh

./bootstrap.sh
./configure \
    --prefix=/usr \
    --includedir=\${prefix}/include \
    --bindir=\${prefix}/bin \
    --sbindir=\${prefix}/lib/frr \
    --libdir=\${prefix}/lib/frr \
    --libexecdir=\${prefix}/lib/frr \
    --localstatedir=/var/run/frr \
    --sysconfdir=/etc/frr \
    --with-moduledir=\${prefix}/lib/frr/modules \
    --enable-configfile-mask=0640 \
    --enable-logfile-mask=0640 \
    --enable-snmp=agentx \
    --enable-multipath=64 \
    --enable-user=frr \
    --enable-group=frr \
    --enable-vty-group=frrvty \
    --with-pkg-git-version \
    --with-pkg-extra-version=-MyOwnFRRVersion
    make
    sudo make install
    sudo ldconfig

# 安装配置文件
sudo install -m 775 -o frr -g frr -d /var/log/frr
sudo install -m 775 -o frr -g frrvty -d /usr/local/etc
sudo install -m 640 -o frr -g frrvty tools/etc/frr/vtysh.conf /usr/local/etc/vtysh.conf
sudo install -m 640 -o frr -g frr tools/etc/frr/frr.conf /usr/local/etc/frr.conf
sudo install -m 640 -o frr -g frr tools/etc/frr/daemons.conf /usr/local/etc/daemons.conf
sudo install -m 640 -o frr -g frr tools/etc/frr/daemons /usr/local/etc/daemons

sudo install -m 644 tools/frr.service /etc/systemd/system/frr.service
sudo systemctl enable frr

